name: Email Auth

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/emailauth.yml'
      - 'FirebaseEmailAuthUI/**'
      - 'test.sh'
      - 'FirebaseEmailAuthUI.podspec'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/emailauth.yml'
      - 'FirebaseEmailAuthUI/**'
      - 'test.sh'
      - 'FirebaseEmailAuthUI.podspec'

  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup
        run: |
          cd FirebaseEmailAuthUI
          gem install bundler
          bundle install
          gem install xcpretty
          bundle exec pod install --repo-update
      - name: Build
        run: |
          ./test.sh FirebaseEmailAuthUI
