name: Facebook Auth

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/facebookauth.yml'
      - 'FirebaseFacebookAuthUI/**'
      - 'test.sh'
      - 'FirebaseFacebookAuthUI.podspec'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/facebookauth.yml'
      - 'FirebaseFacebookAuthUI/**'
      - 'test.sh'
      - 'FirebaseFacebookAuthUI.podspec'

  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup
        run: |
          cd FirebaseFacebookAuthUI
          gem install bundler
          bundle install
          gem install xcpretty
          bundle exec pod install --repo-update
      - name: Build
        run: |
          ./test.sh FirebaseFacebookAuthUI
