name: Google Auth

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/googleauth.yml'
      - 'FirebaseGoogleAuthUI/**'
      - 'test.sh'
      - 'FirebaseGoogleAuthUI.podspec'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/googleauth.yml'
      - 'FirebaseGoogleAuthUI/**'
      - 'test.sh'
      - 'FirebaseGoogleAuthUI.podspec'

  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup
        run: |
          cd FirebaseGoogleAuthUI
          gem install bundler
          bundle install
          gem install xcpretty
          bundle exec pod install --repo-update
      - name: Build
        run: |
          ./test.sh FirebaseGoogleAuthUI
