name: OAuth

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/oauth.yml'
      - 'FirebaseOAuthUI/**'
      - 'test.sh'
      - 'FirebaseOAuthUI.podspec'
      - 'Package.swift'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/oauth.yml'
      - 'FirebaseOAuthUI/**'
      - 'test.sh'
      - 'FirebaseOAuthUI.podspec'
      - 'Package.swift'

  workflow_dispatch:

jobs:
  xcodebuild:
    name: xcodebuild
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup
        run: |
          cd FirebaseOAuthUI
          gem install bundler
          bundle install
          gem install xcpretty
          bundle exec pod install --repo-update
      - name: Build
        run: |
          ./test.sh FirebaseOAuthUI
  spm:
    name: spm
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: List
        run: |
          xcodebuild -list
      - name: Build
        run: |
          xcodebuild -scheme FirebaseOAuthUI -sdk iphonesimulator
