name: Storage

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/storage.yml'
      - 'FirebaseStorageUI/**'
      - 'test.sh'
      - 'FirebaseStorageUI.podspec'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/storage.yml'
      - 'FirebaseStorageUI/**'
      - 'test.sh'
      - 'FirebaseStorageUI.podspec'

  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup
        run: |
          cd FirebaseStorageUI
          gem install bundler
          bundle install
          gem install xcpretty
          bundle exec pod install --repo-update
      - name: Build
        run: |
          ./test.sh FirebaseStorageUI
